# Number of days of inactivity before an issue becomes stale
daysUntilStale: 31
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - enhancement
  - bug
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in 31 days. It will be closed if no further activity occurs in 14 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false